### ISSUE TITLE
Randomized Logistic Regression 

### ISSUE THREAD

**Issue by mdinh186** [hofnerb/stabs#25]
Hi there, 

Can I use the function 'stabsel' for multinomial classification after factorizing the class? 

If so, how does this compare to 'RandomizedLogisticRegression' from sklearn? 

Thank you!

**Comment by hofnerb** [comment]
I am sorry bit I do not understand your question. 

Perhaps you should first read the relevant literature on stability selection (see [1] and the references therein), which is an approach aiming at finding the right (i.e., stable) variables in any variable selection approach. The type of model (such as multinomial regression, logistic regression, ...) is of no importance whatsoever. What counts is that the approach includes variable selection. 

I don't know `RandomizedLogisticRegression` from **sklearn** and don't even know the goal of the implemented function (other than to presumably estimate a logistic regression model). Hence, the comparison to other approaches is up to you...

----
**References:**

[1] B. Hofner, L. Boccuto and M. Göker (2015). "Controlling false discoveries in high-dimensional situations: Boosting with stability selection". BMC Bioinformatics, 16:144. DOI [10.1186/s12859-015-0575-3](http://dx.doi.org/10.1186/s12859-015-0575-3)
