### ISSUE TITLE
no variables are selected 

### ISSUE THREAD

**Issue by Gambleruin** [hofnerb/stabs#27]
Hello hofnerb,
     If I do not fix my lambda, the algorithm would not select any of the variables in the high dimensional data that I have. here is the code and the outcome: 

stab_lasso<-stabsel(x =train_dat, y =tr_target, fitfun =glmnet.lasso, cutoff =0.75,PFER =1)
Stability Selection with unimodality assumption

No variables selected

**Comment by hofnerb** [comment]
Duplace to #26
